#![cfg_attr(not(any(test, feature = "export-abi")), no_main)]

#[cfg(not(any(test, feature = "export-abi")))]
#[no_mangle]
pub extern "C" fn main() {}

#[cfg(feature = "export-abi")]
fn main() {
    // No-op main for ABI export builds. The ABI will be generated by Stylus tooling
    // from the #[public] interfaces defined in the library (e.g., CoffeeFactory).
}
